services:
  http:
    volumes:
      - ./db/dev:/app/db:rw
      - ./configs/config.dev.yaml:/app/config.yaml:ro
      - ./web:/app/web:ro
    environment:
      - CONFIG_FILE=/app/config.yaml
    ports:
      - "32356:32356"
    depends_on:
      - mq

  logger:
    volumes:
      - ./db/dev:/app/db:rw
      - ./configs/config.dev.yaml:/app/config.yaml:ro
    environment:
      - CONFIG_FILE=/app/config.yaml
    depends_on:
      - mq

  mq:
    image: rabbitmq:3.9.13-management-alpine
    user: rabbitmq:rabbitmq
    volumes:
      - ./docker/mq/enabled_plugins:/app/enabled_plugins:ro
      - ./docker/mq/mq.conf:/app/mq.conf:ro
      - ./configs/mq.json:/app/definitions.json:ro
    environment:
      - RABBITMQ_DEFAULT_PASS=mq
      - RABBITMQ_DEFAULT_USER=mq
      - RABBITMQ_ENABLED_PLUGINS_FILE=/app/enabled_plugins
      - RABBITMQ_CONFIG_FILE=/app/mq.conf
    ports:
      - "15672:15672" # management port
      - "5672:5672" # AMQP port

  couchdb:
    environment:
      - COUCHDB_USER=couchdb
      - COUCHDB_PASSWORD=couchdb
    ports:
      - "5984:5984"
