version: '3.7'
services:
  server:
    build:
      dockerfile: ./docker/Dockerfile.server
      context: .
    volumes:
      - ./data:/data:rw
      - ./configs/config.dev.yaml:/app/config.yaml:ro
      - ./web:/app/web:ro
    ports:
      - "8095:8090"
    environment:
      - CONFIG_FILE=/app/config.yaml
