services:
  http:
    build:
      dockerfile: ./docker/Dockerfile
      context: .
      target: app
      args:
        - APP=http
        - TARGETOS=linux
        - TARGETARCH=amd64
    depends_on:
      - mq
      - couchdb

  logger:
    build:
      dockerfile: ./docker/Dockerfile
      context: .
      target: app
      args:
        - APP=logger
        - TARGETOS=linux
        - TARGETARCH=amd64
    depends_on:
      - mq
      - couchdb

  mq:
    image: rabbitmq:3.9.13-alpine

  couchdb:
    build:
      context: .
      dockerfile: ./docker/couchdb/Dockerfile
    networks:
      - db
      - default

networks:
  db:
    driver: bridge
    internal: true
