FROM alpine:3.15.0 AS dev

RUN mkdir /app
WORKDIR /app

COPY ./bin/http /app/http

FROM alpine:3.15.0 AS prod

COPY --from=dev /app/http /app/http
COPY ./configs/config.yaml /app/config.yaml
COPY ./web /app/web

CMD ["/app/http"]
