name: Build and Push Docker Image to GitHub Packages

on:
  push:
    branches:
      - master
      - 8-publish-docker-container # TODO: remove it later

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}


jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    strategy:
      matrix:
        app: [commander, http, logger]
    steps:
    - uses: actions/checkout@v4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Log in to the Container registry
      uses: docker/login-action@v3.3.0
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push Docker image
      id: push
      uses: docker/build-push-action@v6.7.0
      with:
        platforms: linux/386,linux/amd64,linux/arm/v7,linux/arm64
        build-args: APP=${{ matrix.app }}
        context: ./
        file: ./docker/Dockerfile.${{ matrix.app }}
        target: app
        push: true
        tags: ${{ env.REGISTRY }}/pelyib/wl-${{ matrix.app }}:latest
