name: Build and Push Docker Image to GitHub Packages

on:
  push:
    branches:
      - master
      - 8-publish-docker-container # TODO: remove it later

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # TODO: enable again the original matrix
        goos: [linux]
        goarch: [amd64, arm64]
        app: [commander, http, logger]
        # goos: [linux, windows, darwin]
        # goarch: ["386", amd64, arm64]
        # app: [commander, http, logger]
        # exclude:
        #   - goarch: "386"
        #     goos: darwin
        #   - goarch: arm64
        #     goos: windows
    steps:
    - uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.17.x'
    - name: Build
      run: GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o ${{ github.workspace }}/bin/${{ matrix.app }}-${{ matrix.goos }}-${{ matrix.goarch }} ${{ github.workspace }}/cmd/${{ matrix.app }}
    - name: Link app
      run: rm -f ${{ github.workspace }}/bin/${{ matrix.app }} && cp ${{ github.workspace }}/bin/${{ matrix.app }}-${{ matrix.goos }}-${{ matrix.goarch }} ${{ github.workspace }}/${{ matrix.app }}
    - name: Log in to the Container registry
      uses: docker/login-action@v3.3.0
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push Docker image
      id: push
      # run: docker build --push -t ${{ github.actor }}/weather-logger-${{ matrix.app }}:latest -f ${{ github.workspace }}/docker/Dockerfile.${{ matrix.app }} ${{ github.workspace }}
      uses: docker/build-push-action@v6.7.0
      with:
        platforms: ${{ matrix.goos }}/${{ matrix.goarch }}
        context: ./
        file: ./docker/Dockerfile.${{ matrix.app }}
        target: dev
        push: true
        tags: pelyib/weather-logger-${{ matrix.app }}:latest
